spring:
    application:
        name: JavaSamaple
    datasource:
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sample
    jpa:
        hibernate:
            ddl-auto: update
